spring:
  profiles.active: default
---
spring:
  profiles: default
spring.datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost/caf_assignment1
  username: root
  password:
  schema:
  data:
---
spring:
  profiles: test
spring.datasource:
  driverClassName: org.h2.Driver
  url: jdbc:h2:mem:sampletest;MODE=MySQL
  schema: caf_assignment1-schema_h2.sql
  data: caf_assignment1-data_h2.sql

  

  